name: ci

on: [push, release]

jobs:
  make-and-docker-push:
    runs-on: ubuntu-20.04
    env:
      TAG: v1.16.0
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.TAG }}
          repository: trojan-gfw/trojan

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Copy from local builder
        id: build_image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: sebuild/trojan:${{ env.TAG }}

      - name: docker push Digest
        run: echo ${{ steps.build_image.outputs.digest }}
