name: ci

on: [push, release]

jobs:
  docker-build-and-push:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: trojan-gfw/trojan

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Make the trojan files
        id: make_trojan
        run: |
          cmake
          make -j $(nproc)

      - name: Get the version
        id: get_version
        run: |
          v="${GITHUB_REF##*/}"
          if [[ "$v" == "master" ]]; then
            echo ::set-output name=VERSION::latest
          else
            echo ::set-output name=VERSION::${v}
          fi

      - name: Copy from builder and build v2ray for amd64 linux
        id: build_image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          tags: sebuild/trojan:${{ steps.get_version.outputs.VERSION }}

      - name: docker push Digest
        run: echo ${{ steps.build_image.outputs.digest }}
